### ISSUE TITLE
Hello~ , are there some details for generating these files?

### ISSUE THREAD

**Issue by hackerchenzhuo** [jialinwu17/MAVEX#1]
![image](https://user-images.githubusercontent.com/42081540/130600257-aeae12c0-ae84-460b-88c5-462d96ab3f2e.png)

**Comment by hackerchenzhuo** [comment]
like data cleaning or answer alignment？

**Comment by jialinwu17** [comment]
Yes, following https://github.com/hengyuan-hu/bottom-up-attention-vqa/blob/392520640e3d9aed0009ddfe207901757b10b9a6/tools/compute_softscore.py

**Comment by hackerchenzhuo** [comment]
> Yes, following https://github.com/hengyuan-hu/bottom-up-attention-vqa/blob/392520640e3d9aed0009ddfe207901757b10b9a6/tools/compute_softscore.py

thanks so much.
By the way, will the file `compute_detailed_score.py`  be used in training stage? (which refers to `MAVEX_hier/tree/main/vqaEval`, I think this is related to the project `GT-Vision-Lab/VQA` as a standard VQA eval process?)

**Comment by jialinwu17** [comment]
No, compute_detailed_score.py will not be used, it is potential for computing scores for each category of question types (I have not tested it yet in this repo,  so I will delete it).

**Comment by hackerchenzhuo** [comment]
> No, compute_detailed_score.py will not be used, it is potential for computing scores for each category of question types (I have not tested it yet in this repo, so I will delete it).

Thanks again : )
